### PR TITLE
Add authentication

### PR DESCRIPTION
**Pull request by vdechenaux**
Hi,

In recent days, uploadpie requires that the user is authenticated

### CODE REVIEW

**Comment by vdechenaux** [comment]
The tests fails because we should give a real password in the test config :thinking:

**Comment by tkotosz** [comment]
Thanks for the PR.

oh, it now requires auth? :( I will have some time to have a look over the weekend. It doesn't sound good to add password to behat.yml. Prob it should be just a path where the password yml available or an environment variable name where the password is stored, or something like that. I will think about it.

**Comment by tkotosz** [comment]
your change is merged to https://github.com/tkotosz/behat-screenshot-image-driver-uploadpie/pull/5 
will be merged to master as well as soon as ci is happy :)

**Comment by tkotosz** [comment]
release tagged, thanks again @vdechenaux  https://github.com/tkotosz/behat-screenshot-image-driver-uploadpie/releases/tag/1.0.3

**Comment by vdechenaux** [comment]
Thank you!

**Pull request closed without merging**
